# Generated by Django 4.2.3 on 2023-07-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "marca",
                    models.CharField(
                        choices=[
                            ("FIAT", "Fiat"),
                            ("CHEVROLET", "Chevrolet"),
                            ("FORD", "Ford"),
                            ("TOYOTA", "Toyota"),
                        ],
                        default="FORD",
                        max_length=20,
                        verbose_name="Marca",
                    ),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "serial_carroceria",
                    models.CharField(max_length=50, verbose_name="Serial Carroceria"),
                ),
                (
                    "serial_motor",
                    models.CharField(max_length=50, verbose_name="Serial Motor"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PARTICULAR", "Particular"),
                            ("TRANSPORTE", "Transporte"),
                            ("CARGA", "Carga"),
                        ],
                        default="PARTICULAR",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("precio", models.IntegerField(verbose_name="Precio")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificacion"
                    ),
                ),
            ],
        ),
    ]
