# Generated by Django 4.2.2 on 2023-07-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiculo",
            options={"permissions": [("visualizar_catalogo", "visulizar catalogo")]},
        ),
    ]
